import { GetStaticProps } from 'next'
import Head from 'next/head'

const ssg = ({name, fetchAt}) => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center w-full h-screen">
        <div>
          <h1 className="text-4xl w-full">{name}</h1>
          <h2 className="text-2xl w-full">{fetchAt}</h2>
        </div>
      </div>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
    const resp = await fetch('https://api.github.com/users/PetersonJFP')
    const data = await resp.json()

    const date = new Date()

    return {
      props: {
        name: data.name,
        fetchAt: date.toUTCString()
      },
      revalidate: 10
    }
}

export default ssg
